org.gradle.caching=true
org.gradle.jvmargs='-Dfile.encoding=UTF-8'
group=io.ballerina
version=4.1.1-SNAPSHOT
systemProp.org.gradle.internal.publish.checksums.insecure=true
spotbugsPluginVersion=6.5.1
shadowJarPluginVersion=8.3.6
downloadPluginVersion=5.4.0
releasePluginVersion=3.1.0
ballerinaLangVersion=2201.14.0

# Standard Library Dependencies
# Stdlib Level 01
stdlibIoVersion=1.8.2
stdlibTimeVersion=2.8.1
stdlibUrlVersion=2.6.2

# Stdlib Level 02
stdlibConstraintVersion=1.7.0
stdlibCryptoVersion=2.13.0
stdlibLogVersion=2.17.1
stdlibOsVersion=1.10.2
stdlibTaskVersion=2.11.2

# Stdlib Level 03
stdlibCacheVersion=3.10.0
stdlibFileVersion=1.14.0
stdlibMimeVersion=2.12.2
stdlibUuidVersion=1.10.0

# Stdlib Level 04
stdlibAuthVersion=2.14.0
stdlibDataJsonDataVersion=1.1.3
stdlibJwtVersion=2.15.2
stdlibOAuth2Version=2.15.0

# Stdlib Level 05
stdlibHttpVersion=2.18.0

# Stdlib Level 06
stdlibGrpcVersion=1.16.0
stdlibWebsubVersion=2.15.1
stdlibWebsubhubVersion=1.16.1

# Stdlib Level 07
stdlibGraphqlVersion=1.18.1

# Observe
observeVersion=1.8.0
observeInternalVersion=1.8.0

ballerinaGradlePluginVersion=4.0.0
jacocoVersion=0.8.14
