/*
 * Copyright (c) 2026, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package io.ballerina.c2c.helm;

import io.ballerina.c2c.KubernetesConstants;
import io.ballerina.c2c.diagnostics.NullLocation;
import io.ballerina.c2c.exceptions.KubernetesPluginException;
import io.ballerina.c2c.handlers.AbstractArtifactHandler;
import io.ballerina.c2c.models.ConfigMapModel;
import io.ballerina.c2c.models.DeploymentModel;
import io.ballerina.c2c.models.JobModel;
import io.ballerina.c2c.models.SecretModel;
import io.ballerina.c2c.util.C2CDiagnosticCodes;
import io.ballerina.c2c.utils.KubernetesUtils;
import io.ballerina.tools.diagnostics.Diagnostic;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;

/**
 * Orchestrates Helm chart generation for the {@code helm} cloud target: writes
 * {@code Chart.yaml}/{@code values.yaml}/{@code .helmignore}/{@code templates/_helpers.tpl}, the
 * workload template (Deployment or Job/CronJob), and -- only when applicable, mirroring what the
 * corresponding {@code handlers/*Handler} would have emitted -- the Service, HPA, ConfigMap and
 * Secret templates.
 * <p>
 * By the time this runs, {@link io.ballerina.c2c.ArtifactManager#createHelmArtifacts} has already
 * run the real {@code handlers/*Handler} classes (against a throwaway directory) so that every
 * model read here (deployment ports populated from services, {@code BAL_CONFIG_FILES} injected,
 * the resolved {@code DockerModel}, autoscaling resolved) is in exactly the same state it would
 * be for the plain {@code k8s} target -- this class only turns that already-resolved state into
 * Helm template text, it never re-derives it.
 *
 * @since 1.0.0
 */
public class HelmChartHandler extends AbstractArtifactHandler {

    @Override
    public void createArtifacts() throws KubernetesPluginException {
        Path chartDir = dataHolder.getHelmArtifactOutputPath();
        Path templatesDir = chartDir.resolve(KubernetesConstants.HELM_TEMPLATES_DIR);
        String chartName = KubernetesUtils.getValidName(dataHolder.getOutputName());
        String version = packageVersion();

        writeFile(chartDir.resolve(KubernetesConstants.HELM_CHART_FILE),
                HelmChartMetadataWriter.chartYaml(chartName, version, version,
                        "A Helm chart for " + dataHolder.getOutputName() + ", generated by the Ballerina "
                                + "Code2Cloud (c2c) compiler plugin."));
        writeFile(chartDir.resolve(KubernetesConstants.HELM_IGNORE_FILE), HelmChartMetadataWriter.helmIgnore());
        writeFile(templatesDir.resolve(KubernetesConstants.HELM_HELPERS_FILE),
                HelmChartMetadataWriter.helpersTpl(chartName));

        if (dataHolder.getJobModel() != null) {
            writeJobArtifacts(chartDir, templatesDir, chartName);
        } else {
            writeDeploymentArtifacts(chartDir, templatesDir, chartName);
        }

        writeFile(templatesDir.resolve("serviceaccount.yaml"),
                HelmServiceAccountTemplateWriter.serviceAccountYaml(chartName));

        for (ConfigMapModel configMapModel : dataHolder.getConfigMapModelSet()) {
            writeFile(templatesDir.resolve("configmap-" + configMapModel.getName() + ".yaml"),
                    HelmConfigMapTemplateWriter.configMapYaml(chartName, configMapModel));
            for (Map.Entry<String, String> entry : configMapModel.getData().entrySet()) {
                writeFile(chartDir.resolve(HelmConfigMapTemplateWriter.filesPath(configMapModel, entry.getKey())),
                        entry.getValue());
            }
        }
        for (SecretModel secretModel : dataHolder.getSecretModelSet()) {
            writeFile(templatesDir.resolve("secret-" + secretModel.getName() + ".yaml"),
                    HelmSecretTemplateWriter.secretYaml(chartName, secretModel));
        }

        OUT.println("\t@helm:Chart");
    }

    private void writeDeploymentArtifacts(Path chartDir, Path templatesDir, String chartName)
            throws KubernetesPluginException {
        DeploymentModel deploymentModel = dataHolder.getDeploymentModel();
        boolean autoscalingEnabled = dataHolder.getPodAutoscalerModel() != null
                && !KubernetesUtils.isBlank(dataHolder.getPodAutoscalerModel().getDeployment());

        writeFile(chartDir.resolve(KubernetesConstants.HELM_VALUES_FILE),
                HelmChartMetadataWriter.deploymentValuesYaml(deploymentModel, dataHolder.getServiceModelList(),
                        autoscalingEnabled ? dataHolder.getPodAutoscalerModel() : null, dataHolder.getDockerModel()));
        writeFile(templatesDir.resolve("deployment.yaml"),
                HelmWorkloadTemplateWriter.deploymentYaml(chartName, deploymentModel));
        writeFile(templatesDir.resolve("hpa.yaml"), HelmHpaTemplateWriter.hpaYaml(chartName));
        if (!dataHolder.getServiceModelList().isEmpty()) {
            writeFile(templatesDir.resolve("service.yaml"), HelmServiceTemplateWriter.serviceYaml(chartName));
        }
    }

    private void writeJobArtifacts(Path chartDir, Path templatesDir, String chartName)
            throws KubernetesPluginException {
        JobModel jobModel = dataHolder.getJobModel();
        writeFile(chartDir.resolve(KubernetesConstants.HELM_VALUES_FILE),
                HelmChartMetadataWriter.jobValuesYaml(jobModel, dataHolder.getDockerModel()));
        String fileName = KubernetesUtils.isBlank(jobModel.getSchedule()) ? "job.yaml" : "cronjob.yaml";
        writeFile(templatesDir.resolve(fileName),
                HelmWorkloadTemplateWriter.jobYaml(chartName, jobModel, dataHolder.getSecretModelSet(),
                        dataHolder.getConfigMapModelSet()));
    }

    private String packageVersion() {
        if (dataHolder.getPackageID() == null || dataHolder.getPackageID().version == null
                || KubernetesUtils.isBlank(dataHolder.getPackageID().version.getValue())) {
            return "0.0.0";
        }
        return dataHolder.getPackageID().version.getValue();
    }

    private void writeFile(Path path, String content) throws KubernetesPluginException {
        Path parent = path.getParent();
        try {
            if (parent != null) {
                Files.createDirectories(parent);
            }
            Files.writeString(path, content, StandardCharsets.UTF_8);
        } catch (IOException e) {
            Diagnostic diagnostic = C2CDiagnosticCodes.createDiagnostic(C2CDiagnosticCodes.ARTIFACT_GEN_FAILED,
                    new NullLocation(), "helm chart file", path.toString());
            throw new KubernetesPluginException(diagnostic);
        }
    }
}
