[container.image]
name = "build-arg"
repository = "xlight05"
tag = "1.0.0"

[settings]
buildImage = false

[graalvm.builder]
base = "ghcr.io/graalvm/native-image-community:21-muslib-ol9"
buildCmd = "native-image -jar custom_builder.jar -H:Name=custom_builder --no-fallback --static --libc=musl"
